### ISSUE TITLE
Ocean level does not adjust with height level

### ISSUE THREAD

**Issue by Winddbourne** [ezterry/Biome-Height-Tweaker#1]
It is great to be able to change the base height of each biome . . . but when we lower them the ocean level doesn't change to compensate and there is no entry to adjust it.  I went through lowering the entire world by -1 figuring that would place the average height of the world to the vanilla ocean biome's base height.

I wanted to do this because I was going to use world drop to enter the cave dimensions from "Caverns" and thus save block area and system resources by mostly eliminating the underground from the overworld . . . which would allow for more overworld generation with less issues (I hoped). 

But doing so put most of the world underwater, often DEEP under water.  I figure this is an oversight or a bug . . . base biome height should never be under water. lol

**Comment by ezterry** [comment]
I'm trying to remember my experiments but I think -1 is half way between sea level and bedrock in default terrain (y=32) if you want to actually change the sea level use the customized world type and set the sea level. (If you want this lower level to be the default in a modpack use the mod: default world generator-port.). if you want a uniform lowering of terrain you can probably just use customized world settings, if you also want to have per biome customization a hybrid of that and biome height tweaker may work better.

Hope this helps.
